In [5]:
import pandas as pd

read_file = pd.read_csv (r'Resources/South Korea Vaccinations.txt')
read_file.to_csv (r'Resources/South Korea Vaccinations.csv', index=None)
read_file.head(70)

,location,date,vaccine,source_url,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters
0,South Korea,2021-02-26,Oxford/AstraZeneca,https://ncv.kdca.go.kr/,24540,22694,1854,NaN
1,South Korea,2021-02-27,"Oxford/AstraZeneca, Pfizer/BioNTech",https://ncv.kdca.go.kr/,25966,24120,1854,NaN
2,South Korea,2021-02-28,"Oxford/AstraZeneca, Pfizer/BioNTech",https://ncv.kdca.go.kr/,26830,24984,1854,NaN
3,South Korea,2021-03-01,"Oxford/AstraZeneca, Pfizer/BioNTech",https://ncv.kdca.go.kr/,28364,26518,1856,NaN
4,South Korea,2021-03-02,"Oxford/AstraZeneca, Pfizer/BioNTech",https://ncv.kdca.go.kr/,94794,92946,1858,NaN
...,...,...,...,...,...,...,...,...
65,South Korea,2021-05-02,"Oxford/AstraZeneca, Pfizer/BioNTech",https://ncv.kdca.go.kr/,3658928,3419171,250195,NaN
66,South Korea,2021-05-03,"Oxford/AstraZeneca, Pfizer/BioNTech",https://ncv.kdca.go.kr/,3776242,3505903,281308,NaN
67,South Korea,2021-05-04,"Oxford/AstraZeneca, Pfizer/BioNTech",https://ncv.kdca.go.kr/,3882720,3581142,312948,NaN
68,South Korea,2021-05-05,"Oxford/AstraZeneca, Pfizer/BioNTech",https://ncv.kdca.go.kr/,3913628,3586738,338335,NaN
69,South Korea,2021-05-06,"Oxford/AstraZeneca, Pfizer/BioNTech",https://ncv.kdca.go.kr/,4045041,3644634,412189,NaN

In [2]:
clean_df = read_file[read_file['total_vaccinations'] > 0].reset_index( drop = True)
clean_df = clean_df.drop(columns=['source_url', 'total_boosters'])
clean_df

,location,date,vaccine,total_vaccinations,people_vaccinated,people_fully_vaccinated
0,South Korea,2021-02-26,Oxford/AstraZeneca,24540,22694,1854
1,South Korea,2021-02-27,"Oxford/AstraZeneca, Pfizer/BioNTech",25966,24120,1854
2,South Korea,2021-02-28,"Oxford/AstraZeneca, Pfizer/BioNTech",26830,24984,1854
3,South Korea,2021-03-01,"Oxford/AstraZeneca, Pfizer/BioNTech",28364,26518,1856
4,South Korea,2021-03-02,"Oxford/AstraZeneca, Pfizer/BioNTech",94794,92946,1858
...,...,...,...,...,...,...
198,South Korea,2021-09-12,"Oxford/AstraZeneca, Pfizer/BioNTech, Johnson&J...",51918096,33180367,20088923
199,South Korea,2021-09-13,"Oxford/AstraZeneca, Pfizer/BioNTech, Johnson&J...",53161664,34008332,20511816
200,South Korea,2021-09-14,"Oxford/AstraZeneca, Pfizer/BioNTech, Johnson&J...",53977761,34610262,20736211
201,South Korea,2021-09-15,"Oxford/AstraZeneca, Pfizer/BioNTech, Johnson&J...",54783645,34986293,21176113
202,South Korea,2021-09-16,"Oxford/AstraZeneca, Pfizer/BioNTech, Johnson&J...",55514851,35414516,21489009